spring.application.name=movieflix

spring.datasource.url=${ACCESS_DB_URL}
spring.datasource.username=${ACCESS_DB_USER}
spring.datasource.password=${ACCESS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.dialect=postgresql

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
