spring:
  application:
    name: movieflix

  spring:
    datasource:
      url: ${ACCESS_DB_URL}
      username: ${ACCESS_DB_USER}
      password: ${ACCESS_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

movieflix:
  security:
    secret: ${CHAVE_SECRETA}
